### ISSUE TITLE
Special characters are not escaped in the solr query

### ISSUE THREAD

**Issue by Krishanx92** [wso2/carbon-registry#260]
**Description:**
Create special character role and assign it to store user, then login to store to view list of API give error.

**Affected Product Version:**
APIM 2.1.0

**Steps to reproduce:**
1. Create a role with a special character (Eg: test:new)
2. Add the created role to a store user.
3. Login to the store to list the APIs and the error will be logged in the console.

**Comment by daneshk** [comment]
This is fixed with #217. Hence closing the issue
