### ISSUE TITLE
Jenkins Build Failure due to bytecode validation error in Unit Testcase

### ISSUE THREAD

**Issue by daneshk** [wso2/carbon-registry#266]
**Description:**
in jenkins build, SolrClientTestCase is failing due to bytecode validation error. we are currently disable the testcase till we fix the issue. This issue to track the failure.

**Suggested Labels:**
bug

**Suggested Assignees:**
daneshk

**OS, DB, other environment details and versions:**    
Jenkins environment

**Comment by cnapagoda** [comment]
Fixed with #267
